apiVersion: v1
kind: Pod
metadata:
  name: livegrep-indexer
  namespace: default
spec:
  containers:
  - args:
    - /livegrep/bin/livegrep-reindex
    image: docker.io/livegrep/indexer:b1193df7fd-4
    name: indexer
    resources:
      requests:
        cpu: 1
        memory: 4G
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tdvkc
      readOnly: true
    - mountPath: /var/run/secrets/gcp
      name: gcp
      readOnly: true
    - mountPath: /var/run/secrets/ssh
      name: github-ssh
      readOnly: true
    env:
      - name: GITHUB_KEY
        valueFrom:
          secretKeyRef:
            name: github.oauth
            key: oauth_key
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/run/secrets/gcp/service-account.json
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: default-token-tdvkc
    secret:
      defaultMode: 0644
      secretName: default-token-tdvkc
  - name: github-ssh
    secret:
      defaultMode: 0400
      secretName: github.ssh
  - name: gcp
    secret:
      defaultMode: 0644
      secretName: gcp.livegrep-indexer
